---
kind: pipeline
type: kubernetes
name: staging

trigger:
  branch:
    - staging

steps:
  - name: publish-backend
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: s4meer-dev/document-intelligence
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      dockerfile: Dockerfile.backend
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  - name: deploy-backend-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: s4meer-dev
      release: document-intelligence
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/s4meer-dev/document-intelligence"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=document-intelligence.s4meer-dev.staging.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.cpu=2000m"
        - "resources.limits.memory=4096Mi"
        - "resources.requests.cpu=1000m"
        - "resources.requests.memory=2048Mi"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
      values_files: [ "environments/staging.yaml" ]
    when:
      event:
        - push
---
kind: pipeline
type: kubernetes
name: prod

trigger:
  branch:
    - main

steps:
  - name: publish-backend
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: s4meer-dev/document-intelligence
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      dockerfile: Dockerfile.backend
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  - name: deploy-backend-prod
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: s4meer-dev
      release: document-intelligence
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/s4meer-dev/document-intelligence"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=document-intelligence.s4meer-dev.prod.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.cpu=2000m"
        - "resources.limits.memory=4096Mi"
        - "resources.requests.cpu=1000m"
        - "resources.requests.memory=2048Mi"
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
      values_files: [ "environments/prod.yaml" ]
    when:
      event:
        - push